clonezilla:
  root: (hd0,gpt6)
  rootpart: /dev/nvme0n1p6
  backuppart: /dev/nvme0n1p4
  backupdir: Backup
  dirname: live-hd

sudoers:
  cmd: /usr/bin/dnf update, /usr/bin/dnf autoremove -y, /usr/bin/dnf clean all

keyboard:
  path: /usr/share/X11/xkb/symbols/es
  path_backup: /usr/share/X11/xkb/symbols/es.backup
  options: caps:escape,shift:both_capslock,terminate:ctrl_alt_bksp
